id = "c3"
name = "C3"
version = "0.0.3"
schema_version = 1
authors = ["Aiden Olsen <olsenaiden33@gmail.com>", "Chandler Warner <cwarneratwork@proton.me>"]
description = "This extension bring basic c3 language support to zed. NOTE: This extension is still a WIP!"
repository = "https://github.com/Utecha/c3-zed"

[language_servers.c3]
name = "c3lsp"
language = "C3"

[grammars.c3]
repository = "https://github.com/c3lang/tree-sitter-c3"
commit = "c6b1bae4d575f91e5c6c3c4af93bbec4e543ac5e"
